language: haxe

haxe:
  - "3.2.0"
  - "3.1.3"
  - development
 
env: 
  - TARGET=flash
  - TARGET=neko
  - TARGET=cpp
  - TARGET=html5

install:
  - haxelib install lime > /dev/null
  - haxelib install openfl > /dev/null
  - haxelib install hxcpp > /dev/null
  - haxelib install mlib > /dev/null
  - haxelib git flixel https://github.com/HaxeFlixel/flixel > /dev/null
  - haxelib git flixel-templates https://github.com/HaxeFlixel/flixel-templates > /dev/null
  - haxelib dev flixel-tools $TRAVIS_BUILD_DIR
  - haxelib list

script:
  - haxe build.hxml
  - haxelib run flixel-tools tpl -n "default"
  - cd default
  - haxelib run lime build $TARGET
  - cd ..
  - haxelib run flixel-tools tpl barebones -n "barebones"
  - cd barebones
  - haxelib run lime build $TARGET
