language: java

before_script:
  - sudo apt-get install python-software-properties -y
  - sudo add-apt-repository ppa:eyecreate/haxe -y
  - sudo apt-get update
  - sudo apt-get install haxe -y
  - mkdir ~/haxelib
  - haxelib setup ~/haxelib
  - haxelib install openfl
  - haxelib install openfl-native
  - haxelib install openfl-tools
  - haxelib install flixel
  - haxelib git flixel-tools https://github.com/HaxeFlixel/flixel-tools.git mlib_refactor

script:
  - haxelib run flixel-tools download
  - haxelib git flixel https://github.com/HaxeFlixel/flixel.git dev
  - haxelib run flixel-tools validate
