language: haxe

haxe:
  - 3.4.7

env:
  - TARGET=flash
  - TARGET=neko
  - TARGET=html5

install:
  - haxelib git flixel https://github.com/HaxeFlixel/flixel
  - haxe --cwd ~/haxe/lib/flixel/git/tests --run RunTravis flash new -install
  - haxelib dev flixel-tools .

script:
  - haxe build.hxml
  - haxelib run flixel-tools tpl -n "default"
  - cd default
  - haxelib run lime build $TARGET
